pro1/online/urls.py
from django.urls import path
from online import views
from django.conf import settings
from django.conf.urls.static import static
app_name='online'
urlpatterns=[
    path('item/',views.itemsview, name="itemsview"),
    path('product/',views.productview, name="productview"),
    path('details/',views.productdetails, name="productdetails"),
    path('modify/<pk>/',views.productmodify, name="productmodify"),
    path('delete/<pk>/',views.productdelete, name="productdelete"),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro1/pro20/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import online
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('online.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro1/online/models.py
from django.db import models

# Create your models here.

class itemsmodel(models.Model):
    itemname = models.CharField(max_length=30)
    def __str__(self):
        return str(self.itemname)
    
class productmodel(models.Model):
    pname= models.CharField(max_length=30)
    pdesc= models.CharField(max_length=50)
    pprice= models.FloatField()
    pdiscount= models.FloatField()
    ppic = models.ImageField()
    itemid=models.ForeignKey(itemsmodel, on_delete=models.CASCADE)
    
    
    

pro1/online/forms.py
from django import forms
from online.models import * 

class itemsform(forms.ModelForm):
    class Meta:
        model = itemsmodel
        fields = '__all__'
        
class productform(forms.ModelForm):
    class Meta:
        model =productmodel
        fields = '__all__'

pro1/online/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from online.forms import *
from online.models import * 
from django.contrib import messages

# Create your views here.


def itemsview(request):
    if request.method=='POST':
        form = itemsform(request.POST)
        if form.is_valid():
            form.save()
        
    form = itemsform
    return render(request,'registeritems.html',{'items':form})

def productview(request):
    if request.method=='POST' and request.FILES:
        form1 = productform(request.POST,request.FILES)
        print(form1)
        if form1.is_valid():
            form1.save()
            messages.success(request,"product is created")
        else:
            messages.error(request,"product is not created")
    form1 = productform()
    return render(request,'registeritems.html',{'product':form1})

def productdetails(request):
    res=productmodel.objects.all()
    return render(request,"details.html",{'res':res})

def productmodify(request,pk):
    if request.method=='POST' or request.FILES:
        var = productmodel.objects.get(id=pk)
        form1 = productform(request.POST, request.FILES, instance=var)
        if form1.is_valid():
            print("hai")
            form1.save()
            messages.success(request,'your product is modified')
        else:
            messages.error(request,'your product data is not modified')

    res1=productmodel.objects.get(id=pk)
    return render(request,'modify.html',{'res':res1})


def productdelete(request,pk):
    res= productmodel.objects.filter(id=pk).delete()
    res= productmodel.objects.all()
    return render(request,'delete.html',{'res':res})



'''
def productmodify(request,pk):  
    if request.method=='POST' or request.FILES:
        res1 =productmodel.objects.get(id=pk)
        res1.pname = request.POST['pname']
        res1.pdesc = request.POST['pdesc']
        res1.pprice = request.POST['pprice']
        res1.pdiscount = request.POST['pdiscount']
        res1.ppic = request.FILES['ppic']
        res1.save()   
        print("hai") 
    res1=productmodel.objects.get(id=pk)
    return render(request,"modify.html",{'res':res1})
'''

pro1/online/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to details</h1>
    <table border="2">
        <thead><td>NAME</td><td>DESCRIPTION</td><td>PRICE</td><td>DISCOUNT</td><td>PICTURE</t>
        </thead>
        {% for i in res%}
        <tr><td>{{i.pname}}</td>
            <td>{{i.pdesc}}</td>
            <td>{{i.pprice}}</td>
            <td>{{i.pdiscount}}</td>
            <td><img src="{{i.ppic.url}}" alt="no image" height="75" width="100"></td>
        </tr>
        {% endfor %}
        </table>
        <br>
        <a href="/product/"> product</a><br>
        <a href="/details/"> details</a>
        
</body>
</html>

pro1/online/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to product details</h1>
    <table border="2">
        <thead><td>NAME</td><td>DESCRIPTION</td><td>PRICE</td><td>DISCOUNT</td><td>PICTURE</t>
        </thead>
        {% for i in res %}
        <tr><td>{{i.pname}}</td>
            <td>{{i.pdesc}}</td>
            <td>{{i.pprice}}</td>
            <td>{{i.pdiscount}}</td>
            <td><img src="{{i.ppic.url}}" alt="no image" height="75" width="100"></td>
            <td><a href="/modify/{{i.id}}/">modify</a></td>
            <td><a href="/delete/{{i.id}}/">delete</a></td>
        </tr>
        {% endfor %}
        </table>
        <br>
        <a href="/product/"> product</a>
        
</body>
</html>

pro1/online/templates/modify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>welcome to product modify</h1>

    {% for msg in messages %}
    <div>
        <strong>{{msg}}</strong>
        </div>

    {% endfor %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    <table>
<tr><th><label for="id_pname">Pname:</label></th><td><input type="text" name="pname" value={{res.pname}} maxlength="30" required id="id_pname"></td></tr>
<tr><th><label for="id_pdesc">Pdesc:</label></th><td><input type="text" name="pdesc" value={{res.pdesc}} maxlength="50" required id="id_pdesc"></td></tr>
<tr><th><label for="id_pprice">Pprice:</label></th><td><input type="number" name="pprice" value={{res.pprice}} step="any" required id="id_pprice"></td></tr>
<tr><th><label for="id_pdiscount">Pdiscount:</label></th><td><input type="number" name="pdiscount" value={{res.pdiscount}} step="any" required id="id_pdiscount"></td></tr>
<tr><th><label for="id_ppic">Ppic:</label></th><td><input type="file" name="ppic" accept="image/*"></td></tr>
<tr><th><label for="id_itemid">Itemid:</label></th><td><select name="itemid" required id="id_itemid">

  <option value="1" selected>mobile</option> </select></td></tr>
<tr><th><label >existing pic:</label></th><td><img src="{{res.ppic.url}}" alt="no image" height="75" width="100"></td></tr>

</table>
    <input type="submit" value="modify">
</form>
<a href="/details/"> details</a>
<a href="/product/"> product</a>

</body>
</html>

pro1/online/templates/registeritems.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>items and product page</h1>

    {% for msg in messages %}
    <div>
        <strong>{{msg}}</strong>
        </div>

    {% endfor %}

    {% if items %}
        <form method="POST">
            {% csrf_token %}
            {{items.as_p}}
            <input type="submit" value="register">
            </form>

    {% endif %}


    {% if product %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{product.as_p}}
            <input type="submit" value="register">
            </form>

    {% endif %}

</body>
</html>